// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// findDiscSum
int findDiscSum(int s, int m, Rcpp::NumericVector& u, Rcpp::NumericVector& v, Rcpp::NumericVector& cs);
RcppExport SEXP _nout_findDiscSum(SEXP sSEXP, SEXP mSEXP, SEXP uSEXP, SEXP vSEXP, SEXP csSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type u(uSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type v(vSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type cs(csSEXP);
    rcpp_result_gen = Rcpp::wrap(findDiscSum(s, m, u, v, cs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nout_findDiscSum", (DL_FUNC) &_nout_findDiscSum, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_nout(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
