# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findDiscSum <- function(s, m, u, v, cs) {
    .Call(`_nout_findDiscSum`, s, m, u, v, cs)
}

